starting_lives: 3 # Number of lives with which the players or server will start
global_lives: true # true : Players will share lives with the server | false : Players will have their own lives
#death_movement: true # Allow movement after hitting permadeath. If unset, defaults to the value of global_lives
natural_regeneration: true # Enable or disable natural regeneration for all worlds. For the most hardcore experience, set this to 'false'
language: en_EN # For changing the language of the plugin - NOT FULLY SUPPORTED
