name: Hardcorelife
version: ${project.version}
main: hardcorelife.chryscorelab.Touchy
api-version: 1.16
load: POSTWORLD
authors: [DaFray31, drewburr]
description: Hardcorelife
softdepend: [Vault]
commands:
  lives:
  setlives:
