name: NotSoHardcore
version: ${project.version}
main: notsohardcore.chryscorelab.Touchy
api-version: 1.16
load: POSTWORLD
authors: [DaFray31, drewburr]
description: NotSoHardcore
softdepend: [Vault]
commands:
  howmanylives:
