name: NotSoHardcore
version: ${project.version}
main: notsohardcore.drewburr.Touchy
api-version: 1.16
load: POSTWORLD
authors: [drewburr]
description: NotSoHardcore
softdepend: [Vault]
commands:
  howmanylives:
