name: Hardcorelife
version: ${project.version}
main: hardcorelife.chryscorelab.Touchy
api-version: 1.16
load: STARTUP
authors: [DaFray31, drewburr]
description: Hardcorelife
softdepend: [Vault]
commands:
  lives:
    description: Show a player's current life count
    usage: \lives [player]
  setlives:
    description: Set the life count of a player
    usage: \setlives [player] <value>
    permission: hardcorelife.setlives
  resetserver:
    description: Reset all worlds and life values
    usage: Deletes all world data and life values! Use '\resetserver true' to confirm.
    permission: hardcorelife.resetserver
permissions:
  hardcorelife.setlives:
    description: Allow the command /setlives - Set the life count of a player
    default: op
  hardcorelife.resetserver:
    description: Allow the command /resetserver - Reset all worlds and life values
    default: op
